[project]
name = "Maluio's Blog"
version = "0.1.0"
description = "Maluio's Blog"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "invoke>=2.2.1",
    "livereload>=2.7.1",
    "pelican[markdown]>=4.11.0.post0",
]
